name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache deps
        uses: actions/cache@main
        with:
          path: |
            node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache built sources
        uses: actions/cache@main
        with:
          path: |
            dist
          key: ${{ runner.os }}-dist-${ GITHUB_SHA }
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: Build
        run: yarn build

  deploy-eth-mainnet:
    needs: build
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'main') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cache deps
        uses: actions/cache@main
        with:
          path: |
            node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache built sources
        uses: actions/cache@main
        with:
          path: |
            dist
          key: ${{ runner.os }}-dist-${ GITHUB_SHA }
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_KHAOS_ETH_MAINNET_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: khaos-eth-mainnet

  deploy-eth-ropsten:
    needs: build
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'main') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cache deps
        uses: actions/cache@main
        with:
          path: |
            node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache built sources
        uses: actions/cache@main
        with:
          path: |
            dist
          key: ${{ runner.os }}-dist-${ GITHUB_SHA }
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_KHAOS_ETH_ROPSTEN_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: khaos-eth-ropsten
